name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: problem1_test1
      id: problem1_test1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: problem1_test1
        setup-command: ''
        command: "./task1_solution.py"
        input: '2'
        expected-output: Число четное
        comparison-method: exact
        timeout: 1
    - name: p1t2
      id: p1t2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: p1t2
        setup-command: ''
        command: task1_solution.py
        input: '3'
        expected-output: Число нечетное
        comparison-method: exact
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PROBLEM1_TEST1_RESULTS: "${{steps.problem1_test1.outputs.result}}"
        P1T2_RESULTS: "${{steps.p1t2.outputs.result}}"
      with:
        runners: problem1_test1,p1t2
